name: bp-env-gpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - transformers=4.36.1
  - mlflow=2.9.2
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.1.1
  - matplotlib
  - onnx==1.16.2
  - onnxruntime-gpu=1.17.0
  - python-dotenv
  - tqdm
  - pip=22.3.1
  - xgboost=2.1.1
  - pip:
      - tensorflow==2.14.0
      - keras==2.14.0
      - tldextract
      - ipykernel